### ISSUE TITLE
QmlRegisterType max 60 types

### ISSUE THREAD

**Issue by nallath** [fieldOfView/Cura-TabbedSettingsPlugin#7]
So this is an annoying issue that we just ran into (and is also not really documented anywhere..). Basicly, you can only register 60 QML types with pyqt. We could bump this number up for Cura, but that would mean that we have to compile stuff ourself, which although a more permanent solution, is something that would require a bit more time.

If you enable a whole bunch of plugins, Cura basicly refuses to boot at all (aka; You install all plugins in the marketplace ;))

We are going to have a long hard look at what types we are registering, but it's a bit trickier for Cura to move those down as they are technically part of the SDK and removing any of the types we have is also, technically, an SDK break (which is undesirable for obvious reasons).

So; Would it be doable for you to check if you can reduce the number of qml types that you register? It would provide us with a bit more breathing room to look at other solutions going forward.

**Comment by fieldOfView** [comment]
I vaguely remember (now) that this was an issue when we were working on Cura 2.1 still, but would have hoped it was fixed by now. Is the limitation documented anywhere? Can the limit be worked around by using a different namespace, or is it simply one limit for all types?

In this case I guess I can refactor the code to create only a single type instead of 3; they are all SettingVisibilityHandlers so I think it should be doable to create one "switchable" handler instead of 3 distinct ones. However some of my other plugins (Material Settings and Printer Settings) also have three types to register and there the solution might not be so obvious.

By the way, a quick look at the codebase shows that Cura and Uranium have about 57 types registered directly, but then also registers types for _all_ qml files in Resources ResourceTypes.QmlFiles folders. That's a lot more than 60.

**Comment by nallath** [comment]
It's a limit for all types unfortunately, regardless of scope :( It's also not something that pyqt properly documents. The only way I found out about it because of the sentry crashlogs. I then had to check in the pyqt sourcecode to figure out that they use an array (and not a vector like one would assume) to hold these objects...

It also seems to make a distinction for python objects vs qml ones. So the ones registered as qml are not counted towards this limit. There is some additional magic going on to check if something should be counted or not, so it might be that some of the things that we register don't count towards the budget. Increasing the number is also simple, but it's the having to recompile with that change that makes it annoying.

I've found 17 cases where we are registering one where it's not needed. In those cases instead of creating the object ourselves, we use CuraApplication.create[whateveryouwant](). That function is then just a slot that returns a fresh object. That way you don't have to register it as a type and it works just fine. An example of this is the "TextManager", which can be obtained by CuraApplication.getTextManager()

**Comment by fieldOfView** [comment]
@nallath, see 3599750437f5869720d06659d10f1b2d244d4766. That should do the trick, right?

**Comment by fieldOfView** [comment]
Is qmlRegisterSingletonType similarly affected?

**Comment by nallath** [comment]
> @nallath, see [3599750](https://github.com/fieldOfView/Cura-TabbedSettingsPlugin/commit/3599750437f5869720d06659d10f1b2d244d4766). That should do the trick, right?

Yeah. That should work.

> Is qmlRegisterSingletonType similarly affected?

Kinda; The limit is 30 there.

**Comment by fieldOfView** [comment]
> Kinda

Ok, I'll phase that out too in other plugins.

**Comment by fieldOfView** [comment]
This has been implemented in the current releases of the Tabbed Settings plugin, the SidebarGUI plugin and the Material Settings plugin.
